window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser layout/default/layout_helper".split(" "),function(){var p=Registry.get("crcrc").cr,c=Registry.get("crcrc").crc;Registry.get("convert");Registry.get("parser");var l=Registry.get("i18n"),r=Registry.get("curtain"),n=Registry.get("helper"),E=Registry.get("layout/default/tabview"),v=Registry.get("layout/default/htmlutil");Registry.get("xmlhttprequest");var x=Registry.get("layout"),
y=Registry.get("layout/default/layout_helper"),F=y.images;x.render(function(){y.addStyle();y.addFont();var x=$.Deferred,k=null,z="???",t=null,A=function(){var a=document.getElementById("ask"),h=c("div","main_container p100100","ask","main");if(a){var b=a.parentNode;b.removeChild(a);b.appendChild(h);document.body.setAttribute("class","main")}var a=c("div","head_container","ask","head_container"),b=c("div","tv_container","ask","tv_container"),e=p("a","head_link","ask","head_link");e.href="http://tampermonkey.net";
e.target="_blank";var d=c("div","float margin4","ask","head1"),f=c("img","banner","ask");f.src=chrome.extension.getURL("images/icon128.png");var w=c("div","float head margin4","ask","head2"),l=p("div","fire"),k=c("div","version","version","version");k.textContent=" by Jan Biniok";var q=p("div","search","box","");l.textContent="Tampermonkey";d.appendChild(f);w.appendChild(l);w.appendChild(k);e.appendChild(d);e.appendChild(w);a.appendChild(e);a.appendChild(q);h.appendChild(a);h.appendChild(b);h=E.create("_main",
b);a=p("div","main","main","tab_content_h");a.textContent=z;b=p("div","main","main","tab_content");h.appendTab(n.createUniqueId("main","main"),a,b);r.hide();return b},G=function(a){var h=a.script,b=c("div","viewer_bottom","bottom","");a=c("div","editor_400p_outer","editor",h.name);var e=c("div","editor_400p editor_border","editor",h.name),d=c("textarea","editorta","editor",h.name);d.setAttribute("wrap","off");b.appendChild(a);a.appendChild(e);e.appendChild(d);k.nocm?d.value=h.textContent:window.setTimeout(function(){var a=
d.parentNode;a.removeChild(d);b.editor=new MirrorFrame(a,{value:h.textContent,noButtons:!0,matchBrackets:!0})},1);return b},J=function(a){var h=a.script,b=c("div","viewer_last","install"),e=c("div","viewer_content","install_content"),d=c("div","install_buttons","install_buttons");n.select([{label:a.messages.action,fn:H},{label:a.messages.flags.install?l.getMessage("Process_with_Chrome"):null,fn:function(){I(h.fileURL);$(b).hide()}},{label:l.getMessage("Cancel"),fn:s}],function(a){return a.label}).forEach(function(a){var b=
c("input","install","tm",a.label);b.type="button";b.value=a.label;b.addEventListener("click",a.fn);d.appendChild(b)});e.appendChild(d);b.appendChild(e);return b},K=function(a){var h=c("div","viewer_last","import"),b=c("div","viewer_content","import_content"),e=c("div","import_buttons","import_buttons");n.select([{label:l.getMessage("Import"),fn:function(){var b=Object.keys(a);m(k.aid,"import",{data:{import_ids:b}})}},{label:l.getMessage("Cancel"),fn:s}],function(a){return a.label}).forEach(function(a){var b=
c("input","import","tm",a.label);b.type="button";b.value=a.label;b.addEventListener("click",a.fn);e.appendChild(b)});b.appendChild(e);h.appendChild(b);return h},B=function(a,h){var b=a.preparat,e=a.content,d=b.script,f=d.id,k=c("div","viewer_upper",f),n=c("div","viewer_info","general",f),m=c("div","viewer_content","general_content",f),q=p("h3","install","heading",d.id);if(d.icon||d.icon64){var g=p("img","version","heading",f);g.src=d.icon||d.icon64;q.appendChild(g)}g=p("span","name","heading",f);
g.textContent=d.name;q.appendChild(g);d.version&&(g=c("span","view_version","heading",f),g.textContent="v"==d.version[0]?"":"v",g.textContent+=d.version,q.appendChild(g));n.appendChild(q);h&&b.short_info.unshift({prop:"heading",value:b.messages.heading,label:l.getMessage("Action")});var s=c("table","script_desc",f);b.short_info.forEach(function(a){var b=d[a.prop]||a.value;if(b||!h){var e=c("tr","script_desc",a.prop,f),k=c("td","script_desc",a.prop,f+"dt"),g=c("td","script_desc",a.prop,f+"dd");k.textContent=
a.label?a.label:"";g.textContent=b||l.getMessage("_not_set_");e.appendChild(k);e.appendChild(g);s.appendChild(e)}});m.appendChild(s);var q=c("div","viewer_info","info",f),u;h?u=m:(u=c("div","viewer_content","info_content",f),g=p("h4","action","heading",f),g.textContent=b.messages.heading,u.appendChild(g));var r=c("table","messages","",f),r=c("table","messages","",f);b.messages.info.forEach(function(a){var b=c("tr","messages_desc",a.prop,f),d=c("td","messages_desc",a.prop,f+"dt"),e=c("td","messages_desc",
a.prop,f+"dd");d.textContent=a.label;e.textContent=a.value;b.appendChild(d);b.appendChild(e);r.appendChild(b)});u.appendChild(r);var t=c("table","warnings","",f);b.messages.warnings.forEach(function(a){var b=c("tr","warnings_desc",a,f),d=c("td","warnings_desc",a,f+"dt"),e=c("td","warnings_desc",a,f+"dd");d.innerHTML='<img src="'+F.get("critical")+'"></img>&nbsp;';e.innerHTML=v.safeTagsReplace(a).replace(/\n/,"<br />");b.appendChild(d);b.appendChild(e);t.appendChild(b)});u.appendChild(t);g=function(a,
b,e,h){var k=p("table",a,f),g=0,n={};b.forEach(function(b){if(!(g>h||n[b])){n[b]=!0;var d=c("tr",a+"desc",b,f+g),l=c("td",a+"desc",b,f+g+"dt"),m=c("td",a+"desc",b,f+g+"dd");l.innerHTML=0==g?v.safeTagsReplace(e.label):"&nbsp;";m.innerHTML=g==h?'<span title="'+v.safeTagsReplace(e.warning)+'">...!</span>':v.safeTagsReplace(b);d.appendChild(l);d.appendChild(m);k.appendChild(d);g++}});if((b=d.options.override["use_"+a])&&b.length){b=c("tr",a+"desc","ovverride",f+g);var m=c("td",a+"desc","ovverride",f+
g+"dt"),w=c("td",a+"desc","ovverride",f+g+"dd");m.innerHTML=0==g?v.safeTagsReplace(e.label):"&nbsp;";w.innerHTML=v.safeTagsReplace(" ("+l.getMessage("overwritten_by_user")+")");b.appendChild(m);b.appendChild(w);k.appendChild(b)}u.appendChild(k)};g("includes",(d.includes||[]).concat(d.matches||[]),{label:l.getMessage("Include_s__"),warning:l.getMessage("Attention_Can_not_display_all_includes_")},5);g("excludes",d.excludes,{label:l.getMessage("Exclude_s__"),warning:l.getMessage("Attention_Can_not_display_all_excludes_")},
3);n.appendChild(m);q.appendChild(u);k.appendChild(n);k.appendChild(q);e.appendChild(k);a.install&&e.appendChild(a.install(b));a.editor&&e.appendChild(a.editor(b))},I=function(a){m(k.aid,"abort");window.setTimeout(function(){window.location=a+"#bypass=true"},10)},s=function(a,c){m(k.aid,"abort");window.setTimeout(function(){window.close()},100)},C=function(a,c){m(k.aid,"unload");t&&(window.clearInterval(t),t=null);window.removeEventListener("unload",C)};window.addEventListener("unload",C);var D=function(){window.location.search||
window.location.hash?(k=n.getUrlArgs(),k.aid?(m(k.aid,"preparat").done(function(a){a.i18n&&l.setLocale(a.i18n);z=l.getMessage("Install");if(a.preparat){if("install"==a.type)B({content:A(),preparat:a.preparat,install:J,editor:G});else if("import"==a.type){var h=A();a=a.preparat;h.appendChild(K(a));for(var b in a){var e=a[b],d=c("div","viewer_upper",b);B({content:d,preparat:e},!0);h.appendChild(d)}}t=window.setInterval(L,6E4)}}).fail(function(){s()}),r.wait(l.getMessage("Please_wait___"))):s()):window.onhashchange=
function(){D()}},L=function(){return m(k.aid,"ping",{bg:!0})},H=function(){return m(k.aid,"install")},m=function(a,c,b){b=b||{};var e=x();try{var d={aid:a,method:c};b.data&&n.each(b.data,function(a,c){d[c]=b.data[c]});sendMessage({method:"askCom",data:d},function(a){b.bg||r.hide();a.error?("close"==a.action&&s(),e.reject(a)):e.resolve(a)});b.bg||r.wait(l.getMessage("Please_wait___"))}catch(f){console.warn("sS: "+f.message),e.reject()}return e.promise()};chrome.extension.onMessage.addListener(function(a,
c,b){if("confirm"==a.method)n.confirm(a.msg,function(a){b({confirm:a})});else if("showMsg"==a.method)n.alert(a.msg),b({});else return!1;return!0});D()})});
