Registry.require(["crcrc","helper"],function(){var h=Registry.get("crcrc").cr,k=Registry.get("crcrc").crc,m=Registry.get("helper"),n=function(b,a,d){var e=h("div",a.name,a.id,"input");e.key=a.id;var c=h("input",a.name,a.id,"input",!0);b=b.split("##");c.name=a.name;c.uuid=a.uuid;c.key=a.id;c.oldvalue=a.value;c.value=void 0!=a.value?a.value:"";c.type="text";d&&!c.inserted&&c.addEventListener("change",d);d=k("span","optiondesc",a.name,a.id,"s1");var f=h("span",a.name,a.id,"s2");d.textContent=b[0]+":";
1<b.length&&(f.textContent=b[1]);e.appendChild(d);e.appendChild(c);e.appendChild(f);a.enabledBy&&e.setAttribute("name","enabled_by_"+a.enabledBy);return{elem:e,input:c}},p=function(b,a,d){b=null;b=k("input","button",a.name,a.id,"bu",!0);b.name=a.name;b.uuid=a.uuid;b.key=a.id;b.type="button";b.value=a.name;b.reload=a.reload;b.ignore=a.ignore||a.reload;b.warning=a.warning;a.enabledBy&&b.setAttribute("name","enabled_by_"+a.enabledBy);!b.inserted&&d&&b.addEventListener("click",d);return b},q=function(b,
a,d,e){var c=null,c=k("input","button",b,a,"bu",!0);c.name=b;c.key=a;c.type="button";c.value=d;!c.inserted&&e&&c.addEventListener("click",e);return c},r=function(b){return{"&":"&amp;","<":"&lt;",">":"&gt;"}[b]||b};Registry.register("layout/default/htmlutil","48",{getInfoFromUrl:function(b){if(-1!=b.search(/htt(ps|p):\/\/(\*\/\*|\*)*$/)||-1!=b.search(/\*:\/\/(\*\/\*|\*)*$/)||"*"==b)return{tld:"*"};0==b.search(/\//)&&(b=b.replace(/\([^\)]*\)[\?|\+|\*|\{[^\}]*]*/g,""),b=b.replace(/\[[^\]]*\][\?|\+|\*|\{[^\}]*]*/g,
""),b=b.replace(/^\/|\/$|\^|\$|\\\?.*|#.*|\?|\(|\)|\+|\\|\.\*|/g,""),b=b.replace(/[\-\.a-zA-Z0-9]+\/$/g,""),b=b.replace(/[\-\.a-zA-Z0-9]+\/$/g,""));b=b.replace(/^\*:\/\//,"http://");0!=b.search("http")&&(b="http://"+b);b=b.split("/");if(3>b.length)return null;b=b[2].split(".");if(2>b.length)return null;for(var a=b[b.length-1],d=b[b.length-2],e=[],c=b.length-3;0<=c&&-1==b[c].search("\\*");c--)e.push(b[c]);return{tld:a,dom:d,subdom:e.reverse()}},safeTagsReplace:function(b){return b.replace(/[&<>]/g,
r)},addClass:function(b,a){var d=b.getAttribute("class")||"";-1==d.search(RegExp("[ \t]*"+a+"[ \t]*"))&&(d=(d?d+" ":"")+a);b.setAttribute("class",d)},toggleClass:function(b,a){var d=b.getAttribute("class")||"",e=RegExp("[ \t]*"+a+"[ \t]*"),d=-1!=d.search(e)?d.replace(e,""):(d?d+" ":"")+a;b.setAttribute("class",d)},createValidation:function(b,a){if(b.validation){var d=b.validation,e=h("span",b.name,b.id,"validation",!0);d.imageURL&&e.setAttribute("style",'background-image: url("'+d.imageURL+'"); background-size: 16px auto; height: 20px; width: 20px; background-repeat:no-repeat; display: inline-block; margin-left: 10px; vertical-align: middle;');
e&&(a&&e.addEventListener("click",a),d.msg&&e.setAttribute("title",d.msg))}return e},createEnabler:function(b,a,d,e,c,f,g){b=k("div","clickable enabler "+b,a,d,e,"wrap",!0);c&&(b.title=c);b.key=d;b.uuid=a;b.alt=" ?";b.textContent=g;f&&b.addEventListener("click",f);return b},createImage:function(b,a,d,e,c,f){e=k("img","icon16",a,d,e,!0);e.setAttribute("src",b);f&&(b=e.getAttribute("class")||"",e.setAttribute("class",b+" clickable"));c&&(e.title=c);e.key=d;e.name=a;e.alt=" ?";f&&!e.inserted&&(e.addEventListener("click",
f),e.href="#");return e},createFavicon:function(b,a,d,e){var c=k("img","icon16",a,d,m.filter(e,/[a-zA-Z0-9]/g));if(c.inserted)return c;"Array"!==m.toType(b)&&(b=[b]);a=function(){if(0!=b.length){var a=b.splice(0,1);c.setAttribute("src",a)}};c.addEventListener("error",a);a();e&&(c.title=e);c.alt=" ?";return c},createFileInput:function(b,a,d){b=k("input","import","file",null,null,!0);b.inserted||(b.type="file",d&&b.addEventListener("change",d));return b},createTextarea:function(b,a,d){var e=h("div",
a.name,a.id,"textarea");e.key=a.id;var c=k("textarea","settingsta",a.name,a.id,"textarea",!0);c.name=a.name;c.key=a.id;c.uuid=a.uuid;c.array=a.array;c.oldvalue=a.value;c.value=void 0!=a.value?a.array?a.value.join("\n"):a.value:"";d&&!c.inserted&&c.addEventListener("change",d);a=h("span",a.name,a.id,"s1");b&&(a.textContent=b+":");e.appendChild(a);e.appendChild(c);return{elem:e,textarea:c}},createInput:n,createPassword:function(b,a,d){b=n(b,a,d);b.input.setAttribute("type","password");return b},createCheckbox:function(b,
a,d){var e=k("div","checkbox",a.name,a.id,"cb1");e.key=a.id;var c=h("input",a.name,a.id,"cb",!0);c.title=a.desc?a.desc:"";c.name=a.name;c.uuid=a.uuid;c.key=a.id;c.reload=a.reload;c.warning=a.warning;c.oldvalue=a.enabled;c.checked=a.enabled;c.type="checkbox";c.valtype="boolean";d&&!c.inserted&&c.addEventListener("click",d);d=k("span","checkbox_desc",a.name,a.id,"cb2");d.textContent=b;e.title=a.desc?a.desc:"";e.appendChild(c);e.appendChild(d);return{elem:e,input:c}},createDropDown:function(b,a,d,e){var c=
h("div",a.name,a.id,"outer_dd");c.key=a.id;var f=h("select",a.name,a.id,"dd",!0),g;for(g in d){var l=h("option",a.name,d[g].name,"dd"+a.id,!0);l.textContent=m.decodeHtml(d[g].name);l.value=d[g].value;d[g].enabledBy&&l.setAttribute("name","enabled_by_"+d[g].enabledBy);a.enabler&&d[g].enable&&l.setAttribute("enables",JSON.stringify(d[g].enable));d[g].value==a.value&&(l.selected=!0);f.appendChild(l)}f.key=a.id;f.name=a.name;f.uuid=a.uuid;f.reload=a.reload;f.warning=a.warning;f.oldvalue=a.value;f.valtype=
"native";e&&!f.inserted&&f.addEventListener("change",e);d=k("span","optiondesc",a.name,a.id,"inner_dd");d.textContent=b+": ";c.appendChild(d);c.appendChild(f);c.title=a.desc?a.desc:"";a.enabledBy&&c.setAttribute("name","enabled_by_"+a.enabledBy);return{elem:c,select:f}},createImageButton:function(b,a,d,e,c){var f=null,g=null,h=null,f=k("input","imgbutton button",b,a,"bu",!0),g=k("div","imgbutton_container",b,a,"bu_container");g.appendChild(f);f.uuid=b;f.key=a;f.type="button";h=k("img","imgbutton_image",
b,a,"bu_img",!0);h.src=e;g.appendChild(h);f.setAttribute("title",d);h.setAttribute("title",d);!f.inserted&&c&&(f.addEventListener("click",c),h.addEventListener("click",c));return g},createButton:function(b,a,d,e){return"Object"===m.toType(a)?p.apply(this,arguments):q.apply(this,arguments)},createPosition:function(b,a,d){for(var e=h("div",a.name,a.id,"pos1"),c=h("select",a.name,a.id,"pos",!0),f=1;f<=a.posof;f++){var g=h("option",a.name,a.id,"opt"+f);g.textContent=f;f==a.pos&&(g.selected=!0);c.appendChild(g)}c.key=
a.id;c.uuid=a.uuid;c.name=a.name;d&&!c.inserted&&c.addEventListener("change",d);a=k("span","optiondesc",a.name,a.id,"pos2");a.textContent=b;e.appendChild(a);e.appendChild(c);return e},createSearchBox:function(b){var a=k("div","searchbox","search_inner"),d=k("div","searchbox_mv","search_inner_mv"),e=k("input","searchbox_input","search_input"),c=k("input","searchbox_button","search_button");e.type="text";e.value=b;c.type="button";c.value="Go";var f=function(){window.location=window.location.origin+
window.location.pathname+"?url="+encodeURIComponent(e.value)};c.addEventListener("click",f);e.addEventListener("keyup",function(a){a&&13==a.keyCode&&f()});d.appendChild(e);d.appendChild(c);a.appendChild(d);return a}})});
