Registry.registerRaw("environment.js","48",function(){TMwin.domContentLoaded=!1;TMwin.loadHappened=!1;TMwin.domNodeInserted=!1;TMwin.props={};TMwin.adjustLogLevel=function(a){void 0!==a&&(logLevel=a);D|=60<=logLevel};var p=function(){var a={objs:{},push:function(b,c){0!==c&&1!==c&&(c=0);var e=Math.floor(19831206*Math.random()+1);a.objs[e]={fn:b,prio:c};return e},remove:function(b){delete a.objs[b]},get:function(b){for(var c=[],e=0;1>=e;e++)for(var d in a.objs)a.objs.hasOwnProperty(d)&&
(a.objs[d].prio!==e||void 0!==b&&d!=b||c.push(a.objs[d].fn));return void 0===b?c:c[0]},finalize:function(b){if(void 0===b){b=a.get();for(var c=0;c<b.length;c++)b[c]()}else return a.objs[b]&&(c=a.objs[b].fn(),delete a.objs[b]),c}};return a}();TMwin.adjustLogLevel();var m=TMwin.chromeEmu,N=function(a){return{}.toString.apply(a).match(/\s([a-z|A-Z]+)/)[1]},C=function(a,b){void 0==b&&(b=100);return b&&a&&(a==document||C(a.parentNode,b-1))},R=function(){var a=function(){};a.prototype={};return new a},
X=function(){var a=R(),b=function(a,b,c,d,f,e){var g=c[d];c[d]=e&&"string"===typeof g?new Function(g):function(){return g.apply(f,arguments)};return b.apply(a,c)},c={setTimeout:{enhance:function(){return b(window,window.setTimeout,arguments,0,a,!0)}},setInterval:{enhance:function(){return b(window,window.setInterval,arguments,0,a,!0)}},location:{get:!0,set:function(a){window.location.href=a}},clearInterval:{wrap:!0},clearTimeout:{wrap:!0},addEventListener:{enhance:function(){return b(window,window.addEventListener,
arguments,1,a,!0)}},removeEventListener:{enhance:function(){return b(window,window.removeEventListener,arguments,1,a,!0)}}},e=function(b){return b==window?a:b},d=function(a,b,c,d){c||(c=a);var f=function(){var f=a[b].apply(c,arguments);d&&(f=d(f));return f};f.__proto__=a[b];f.prototype=a[b].prototype;return f},g=function(b){var c=void 0,d=void 0,f=null,f=function(f){c=f;d=function(){return f.apply(a,arguments)};window[b]=d};a.__defineGetter__(b,function(){return void 0===c||d!==window[b]?window[b]:
c});a.__defineSetter__(b,f)},k=function(b,c,d){var f=void 0,g=null,k=null,g="function"===typeof c.get?c.get:function(){d&&d.get_cb&&d.get_cb.apply(this,arguments);return void 0===f?e(window[b]):f};"function"===typeof c.set?k=c.set:c.get||(k=function(a){d&&d.set_cb&&d.set_cb.apply(this,arguments);return f=a});g&&a.__defineGetter__(b,g);k&&a.__defineSetter__(b,k)};(function(){var a=0,b=function(b){for(var c=a;c<b;c++)k(String(c),{get:!0});a=Math.max(b,a)};k("length",{},{get_cb:function(){b(window.frames.length)}});
b(Math.max(window.frames.length,7))})();for(var f in c)c.hasOwnProperty(f)&&(TMwin.windowProps[f]=TMwin.windowProps[f]||!1!==c[f]);var h;for(f in TMwin.windowProps)if(TMwin.windowProps.hasOwnProperty(f)&&!1!==c[f]){h={};try{try{c[f]?c[f].wrap?(h.wrap=!0,h.that=c[f].that):c[f].direct?h.direct=!0:c[f].enhance?h.enhance=c[f].enhance:c[f].get&&(h.get=c[f].get,h.set=c[f].set):"function"===typeof window[f]?TMwin.windowProps[f].proto?h.wrap=!0:h.direct=!0:"number"===typeof window[f]||"string"===typeof window[f]?
h.get=!0:TMwin.windowProps[f].event&&TMwin.windowProps[f].proto?h.event=!0:h.direct=!0}catch(s){h.get=!0}h.direct?a[f]=e(window[f]):h.enhance?a[f]=h.enhance:h.event?g(f):h.get||h.set?k(f,h):h.wrap&&function(){var b=f;a[b]=d(window,b,h.that,e)}()}catch(l){console.warn("env: error while creating a new sandbox: "+l.message)}}return a},Y=function(a,b,c,e,d){var g=null;try{var k=e.sandboxes[a.id];k.__TMbackref||(k.__TMbackref={});var f="",h='arguments.callee.__tmid = { id: "'+a.id+'", run_at: "'+a.options.run_at+
'", ns: "'+a.namespace+'" };\n',s=["context"],l=[void 0],p;for(p in e.elements[a.id])if(e.elements[a.id].hasOwnProperty(p)){var q=e.elements[a.id][p];q.name?q.overwrite?(s.push(q.name),l.push(q.value)):q.scriptid?(k.__TMbackref[q.name+"_"+q.scriptid]=q.value,s.push(q.name),l.push('context.__TMbackref["'+q.name+"_"+q.scriptid+'"]')):(k[q.name]=q.value,s.push(q.name),l.push("context."+q.name)):D&&console.warn("env: WARN: unexpected item in props elem: "+JSON.stringify(q))}e=[];e.push(h);e.push("with (context) {\n");
e.push("(function(");e.push(s.join(","));e.push(") {");e.push("try {\n");e.push(c);e.push(b);e.push("\n} catch (e) {    if (e.message && e.stack) {        console.error(\"ERROR: Execution of script '"+a.name+'\' failed! " + e.message);        console.log(e.stack.replace(/\\(eval at <anonymous> /g, "").replace(/<anonymous>:/g, "").replace(/chrome-extension:\\/\\/[\\w]{32}\\/content\\.js:\\d*:\\d*\\)*, /g, ""));    } else {        console.error(e);    }};\n');e.push("}).apply(context, [");e.push(l.join(","));
e.push("]);");e.push("}\n");g=e.join("");s=function(a,b){(new Function("context",g)).apply(b,[b])};d?d(s,[g,k]):s(g,k)}catch(v){d={maxerr:999,newcap:!0,es5:!0,sloppy:!0,browser:!0,white:!0,plusplus:!0,nomen:!0,"continue":!0,todo:!0,eqeq:!0,passfail:!1,unparam:!0,devel:!0};k=null;try{k=JSLINT}catch(O){}d=k?k(g,d):!0;k="";if(d)k=f+b;else{f=(h+f).split("\n").length+2;c=c.split("\n").length;var h="",E;for(E in JSLINT.errors)(k=JSLINT.errors[E])&&k.line>=f&&(s=k.line-f+1,h+=s>c?"script: ":"require: ",
h+=k.reason.replace(/.$/,"")+" on line: "+s+" at character: "+k.character+"\n");k="JSLINT output:\n"+h}D||d?(console.error("env: ERROR: Syntax error @ '"+a.name+"'!\n##########################\n"+k+"##########################\nERROR: "+v.message+"\n"),console.error(v.stack)):console.error("env: ERROR: Syntax error @ '"+a.name+"'!\n"+v.message+"\n",v.stack);window.setTimeout(function(){D&&m.extension.sendMessage({method:"copyToClipboard",data:{content:b,type:"test"},id:"42"},function(){});throw v;
},1)}},w=[],l={events:[],done:{},running:null},y=function(a,b,c,e){var d={attrChange:0,attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:(new Date).getTime()};c="string"===typeof c?new Function(c):c;var g=new Event,k;for(k in d)g[k]=d[k];for(k in b)g[k]=b[k];g.type=a;c.apply(e,[g])},F=function(a){TMwin.loadHappened=!0;TMwin.domContentLoaded=
!0;D&&console.log("env: DOMContentLoaded Event!");z()},G=function(a){!TMwin.domNodeInserted&&D&&console.log("env: first DOMNodeInserted Event!");TMwin.loadHappened=!0;TMwin.domNodeInserted=!0;l&&l.events.push({event:a,domContentLoaded:TMwin.domContentLoaded})},H=function(a){TMwin.loadHappened=!0;D&&console.log("env: load Event!")},I=function(){document.removeEventListener("DOMNodeInserted",G,!1);document.removeEventListener("DOMContentLoaded",F,!1);document.removeEventListener("load",H,!1);window.removeEventListener("unload",
I,!1);if(null!=p){for(var a=p.get(),b=0;b<a.length;b++)a[b]();p=null}m.clean&&m.clean()},z=function(){for(var a=w.length;0<w.length;){var b=w.shift();try{window.setTimeout(b.fn,1)}catch(c){console.log("ERROR: Execution (loadListener) of script env "+b.name+" failed!"+c.message)}}return a},J=function(a,b){if(document.body)window.setTimeout(function(){a()},1);else{var c=function(){document.removeEventListener("load",c,!1);document.removeEventListener("DOMNodeInserted",c,!1);document.removeEventListener("DOMContentLoaded",
c,!1);J(a,b)};document.addEventListener("load",c,!1);document.addEventListener("DOMNodeInserted",c,!1);document.addEventListener("DOMContentLoaded",c,!1)}},Z=function(a,b,c){w.push({fn:function(){a()},name:c});TMwin.domContentLoaded?z():D&&console.log("env: schedule for later events!")},K=function(a,b){void 0===b&&(b=20);return 0==b?null:!a.__tmid&&a.caller?K(a.caller,b-1):a.__tmid},S=function(a){p.finalize(a)},P=function(a,b,c){var e=TM_context_id+"#"+a,d=null,d=p.push(function(){m.extension.sendMessage({method:"unRegisterMenuCmd",
name:a,id:e},function(a){})},1);m.extension.sendMessage({method:"registerMenuCmd",name:a,id:TM_context_id,menuId:e,accessKey:c},function(e){e.run&&null!==d&&void 0!==p.get(d)?(window.setTimeout(function(){b()},1),P(a,b,c)):null!==d&&(p.remove(d),d=null)});return d},T=function(a,b){var c=null,e=function(){null===c?window.setTimeout(e,500):0<c?(m.extension.sendMessage({method:"closeTab",tabId:c,id:TM_context_id},d),c=void 0):D&&console.debug("env: attempt to close already closed tab!")},d=function(a){c=
a.tabId};a&&0==a.search(/^\/\//)&&(a=location.protocol+a);m.extension.sendMessage({method:"openInTab",url:a,id:TM_context_id,options:b},d);return{close:e}},U=function(a){var b=!1;a.url&&"/"===a.url.substr(0,1)&&(a.url=window.location.origin+a.url);var c=function(){var a={};Object.getOwnPropertyNames(XMLHttpRequest.__proto__).forEach(function(b){a[b]=!0});var b=function(){};Object.getOwnPropertyNames(XMLHttpRequest).forEach(function(c){a[c]||(b[c]=XMLHttpRequest[c])});return b}(),e=function(a,d){d=
d||{};a&&!b&&window.setTimeout(function(){d.__proto__=c;a.apply(d,[d])},1)};if(a.responseType||"FormData"===N(a.data)){var d,g=new XMLHttpRequest;void 0===a.async&&(a.async=!0);g.open(a.method,a.url,a.async,a.user,a.password);if(a.headers)for(d in a.headers)g.setRequestHeader(d,a.headers[d]);a.overrideMimeType&&g.overrideMimeType(a.overrideMimeType);a.responseType&&(g.responseType=a.responseType);"abort error load progress readystatechange timeout".split(" ").forEach(function(b){g["on"+b]=function(){var c=
"",d=a.url;if(2<g.readyState&&(c=g.getAllResponseHeaders(),4==g.readyState)){c&&(c=c.replace(/TM-finalURL\: .*[\r\n]{1,2}/,""));var l=g.getResponseHeader("TM-finalURL");l&&(d=l)}c={readyState:g.readyState,status:"",statusText:"",responseHeaders:c,finalUrl:d};4==g.readyState&&(g.responseType&&""!=g.responseType?c.response=g.response:(c.responseText=g.responseText,c.responseXML=g.responseXML),c.status=g.status,c.statusText=g.statusText);e(a["on"+b],c)}});g.send(a.data)}else d=m.extension.connect("xhr_"+
TM_context_id),d.postMessage({method:"xhr",details:a,id:TM_context_id}),d.onMessage.addListener(function(b){try{b.success?a.onload&&(b.data.responseXML&&(b.data.responseXML=unescape(b.data.responseXML)),e(a.onload,b.data)):b.change?a.onreadystatechange&&e(a.onreadystatechange,b.data):b.progress?a.onprogress&&e(a.onprogress,b.data):b.timeout?a.ontimeout&&e(a.ontimeout,b.data):a.onerror&&e(a.onerror,b.data)}catch(c){console.log("env: Error: TM_xmlhttpRequest - "+c.message+"\n"+JSON.stringify(a))}});
return{abort:function(){b=!0}}},V=function(a,b){m.extension.sendMessage({method:"installScript",url:a,id:TM_context_id},function(a){b&&b(a)})},$=function(a){var b=[],c=a.storage,e=a.script.uuid,d=a.script,g=null;(function(){g=m.extension.connect("storageListener_"+TM_context_id);g.onMessage.addListener(function(a){if(a.storage)for(var b in a.storage.data)if(a.storage.data.hasOwnProperty(b)){var d=b,e=c.data[b];c.data[b]=a.storage.data[b];h(d,e,c.data[b],!0)}a.removed&&(c[a.removed]=x);a.error&&console.log("env: Error: storage listener... :(")});
g.postMessage({method:"addStorageListener",uuid:e,id:TM_context_id})})();var k=function(a){g.postMessage({method:"saveStorageKey",uuid:e,key:a,value:c.data[a],id:TM_context_id,ts:c.ts})},f=function(a,b,c){c===x&&(c=function(a){return a});var d=[],e=null;if(a&&a.length){var e={GM_info:!0},f;for(f in a)if(a.hasOwnProperty(f)){var g=a[f];e[g]=!0}}for(f in b)b.hasOwnProperty(f)&&(g=b[f],e&&!e[c(g.name)]||d.push(g));return d},h=function(a,c,d,e){if(c!=d)for(var f in b)if(b.hasOwnProperty(f)){var g=b[f];
if(g&&g.key==a&&g.cb)try{g.cb(a,v(c),v(d),e)}catch(k){D&&console.warn("env: value change listener of '"+a+"' failed with: "+k.message)}}},l=function(a,c){var d=0,e;for(e in b)b.hasOwnProperty(e)&&e.id>d&&(d=e.id);d++;b.push({id:d,key:a,cb:c});return d},w=function(a){for(var c in b)if(b.hasOwnProperty(c)&&c.id==a)return delete b[c],!0},t=function(a){var b=c.data[a];c.ts=(new Date).getTime();delete c.data[a];k(a);h(a,b,c.data[a],!1)},q=function(){var a=[],b;for(b in c.data)c.data.hasOwnProperty(b)&&
a.push(b);return a},v=function(a,b){var c=a[0];a=a.substring(1);switch(c){case "b":return"true"==a;case "n":return Number(a);case "o":try{return JSON.parse(a)}catch(d){return console.log("env: parseValueFromStorage: "+d),b}default:return a}},O=function(a,b){var d=c.data[a];return d?v(d,b):b},E=function(a,b){var d=c.data[a],e=(typeof b)[0];switch(e){case "o":try{b=e+JSON.stringify(b)}catch(f){console.log(f);return}break;default:b=e+b}c.ts=(new Date).getTime();c.data[a]=b;k(a);h(a,d,c.data[a],!1)},
y=function(a){for(var b in d.resources){var c=d.resources[b];if(c.name==a)return c.resText}return null},z=function(a){for(var b in d.resources){var c=d.resources[b];if(c.name==a)return c.resURL}return null},C=function(a){window.console?window.console.log(a):console.log(a)},F=function(a){try{var b=document.createElement("style");b.textContent=a;(document.head||document.body||document.documentElement||document).appendChild(b)}catch(c){console.log("Error: env: adding style "+c)}},G=function(b,c,d,e,
f){var g,k=null;c||(c=a.script.name);if(f){var h=typeof f;"number"===h?g=f:"object"===h&&(k=f.onclose,g=f.timeout)}d==x&&(d=a.script.icon?a.script.icon:a.script.icon64);m.extension.sendMessage({method:"notification",delay:g,msg:b,image:d,title:c,id:TM_context_id},function(a){a.clicked&&e&&e();k&&k(!0===a.clicked)})},H=function(a,b,c){var d=typeof b,e="text",f="text/plain";"object"===d?(b.type&&(e=b.type),b.mimetype&&(f=b.mimetype)):"string"===d&&(e=b);m.extension.sendMessage({method:"copyToClipboard",
data:{content:a,type:e,mimetype:f},id:TM_context_id},function(a){c&&c()})},I=function(a){m.extension.sendMessage({method:"getTab",id:TM_context_id,uid:d.uuid},function(b){a&&a(b.data)})},M=function(a,b){m.extension.sendMessage({method:"setTab",id:TM_context_id,tab:a,uid:d.uuid},function(a){b&&b()})},J=function(a){m.extension.sendMessage({method:"getTabs",id:TM_context_id,uid:d.uuid},function(b){a&&a(b.data)})},n=function(a,b){var c=window,d="__u__"+Math.floor(19831206*Math.random()+1),e=d+"_",f=TM_do;
TMwin.use.safeContext&&(window!==unsafeWindow?c=unsafeWindow:f=function(a){(new Function(a))()});c[d]=a;c[e]=b;f=f('window["'+d+'"].apply(this, window["'+e+'"])');delete c[d];delete c[e];return f},x=TMwin.undefined,r=[],A=null,u;for(u in d.grant)if(d.grant.hasOwnProperty(u)&&"none"===d.grant[u]){A=n;break}var B=d.namespace+"_"+!!A;TMwin.props[B]===x&&(TMwin.props[B]={sandboxes:{},elements:{}},p.push(function(){TMwin.props[B]=null}));if(!A&&("sandbox"===TMwin.use.proxy&&r.push({name:"window",value:"context",
overwrite:!0}),!TMwin.use.safeContext)){var Q={window:window};for(u in Q)Q.hasOwnProperty(u)&&function(){var a=u.replace(/^(.)/g,function(a){return a.toUpperCase()});r.push({name:"unsafe"+a,value:Q[u]})}()}r.push({name:"CDATA",value:function(a){this.src=a;this.toXMLString=this.toString=function(){return this.src}}});r.push({name:"uneval",value:function(a){try{return"$1 = "+JSON.stringify(a)+";"}catch(b){console.log(b)}}});"sandbox"!==TMwin.use.proxy&&(r.push({name:"console",value:console}),r.push({name:"JSON",
value:JSON}),r.push({name:"top",value:"window.unsafeTop",overwrite:!0}),r.push({name:"location",value:window.location}),r.push({name:"document",value:window.document}));r.push({name:"undefined",value:x});r.push({name:"define",value:x});r.push({name:"module",value:x});n=[];n.push({name:"TM_addStyle",value:F});n.push({name:"TM_deleteValue",value:t});n.push({name:"TM_listValues",value:q});n.push({name:"TM_getValue",value:O});n.push({name:"TM_log",value:C});n.push({name:"TM_registerMenuCommand",value:P});
n.push({name:"TM_unregisterMenuCommand",value:S});n.push({name:"TM_openInTab",value:T});n.push({name:"TM_setValue",value:E});n.push({name:"TM_addValueChangeListener",value:l});n.push({name:"TM_removeValueChangeListener",value:w});n.push({name:"TM_xmlhttpRequest",value:U});n.push({name:"TM_setClipboard",value:H});n.push({name:"TM_getTab",value:I});n.push({name:"TM_setTab",value:M});n.push({name:"TM_saveTab",value:M});n.push({name:"TM_getTabs",value:J});n.push({name:"TM_installScript",value:V});n.push({name:"TM_notification",
value:G});n.push({name:"TM_getResourceText",value:y,scriptid:d.id});n.push({name:"TM_getResourceURL",value:z,scriptid:d.id});var L=[],K=new function(){this.GM_addStyle=function(a){return F(a)};this.GM_deleteValue=function(a){return t(a)};this.GM_listValues=function(){return q()};this.GM_getValue=function(a,b){return O(a,b)};this.GM_addValueChangeListener=function(a,b){return l(a,b)};this.GM_removeValueChangeListener=function(a){return w(a)};this.GM_log=function(a){return C(a)};this.GM_registerMenuCommand=
function(a,b,c){return P(a,b,c)};this.GM_unregisterMenuCommand=function(a){return S(a)};this.GM_openInTab=function(a,b){return T(a,b)};this.GM_setValue=function(a,b){return E(a,b)};this.GM_xmlhttpRequest=function(a){return U(a)};this.GM_getResourceText=function(a){return y(a)};this.GM_getResourceURL=function(a){return z(a)};this.GM_notification=function(a,b,c,d,e){return G(a,b,c,d,e)};this.GM_installScript=function(a,b){return V(a,b)};this.GM_getTab=function(a){return I(a)};this.GM_setTab=function(a,
b){return M(a,b)};this.GM_saveTab=function(a){return M(a)};this.GM_getTabs=function(a){return J(a)};this.GM_setClipboard=function(a,b,c){return H(a,b,c)};Object.defineProperties(this,{GM_info:{get:function(){var b={observers:1,id:1,enabled:1,hash:1,fileURL:1},c={script:{}},e;for(e in d)d.hasOwnProperty(e)&&!b[e]&&(c.script[e]=d[e]);c.script["run-at"]=d.options.override.run_at||d.options.run_at;c.script.excludes=d.options.override.orig_excludes;c.script.includes=d.options.override.orig_includes;c.script.matches=
d.options.override.orig_includes;c.script.grant=d.grant;c.script.unwrap=!1;b=d.options.updateURL||d.options.fileURL;c.scriptMetaStr=a.header;c.scriptSource=a.code;c.scriptWillUpdate=!!b;c.scriptUpdateURL=b;c.version=a.version;c.scriptHandler="Tampermonkey";c.isIncognito=TMwin.isIncognito;return c},enumerable:!0,configurable:!0}})},W=[];for(u in K)W.push({name:u,value:K[u]});L=L.concat(f(d.grant,n,function(a){return a.replace(/^TM_/,"GM_")}));L=L.concat(f(d.grant,W));r=r.concat(L);d.options.compat_prototypes&&
(D&&console.log("env: option: add toSource"),Object.prototype.toSource||Object.defineProperties(Object.prototype,{toSource:{value:function(){var a=N(this);if("String"===a)return"(String('"+this.replace(/\'/g,"\\'")+"'))";if("Number"===a)return"(Number('"+Number(this)+"'))";if("Array"===a){for(var b="(new Array(",c=0;c<this.length;c++)a=N(this[c]),b="Null"===a?b+"null":"Undefined"===a?b+"undefined":b+this[c].toSource(),c+1<this.length&&(b+=",");return b+"))"}return"JSON.parse(unescape('"+escape(JSON.stringify(this))+
"'))"},enumerable:!1,writable:!0,configurable:!0}}),D&&console.log("env: option: add some array generics"),"indexOf lastIndexOf filter forEach every map some slice".split(" ").forEach(function(a){if("function"!==typeof Array[a]){var b={};b[a]={value:function(b){return Array.prototype[a].apply(b,Array.prototype.slice.call(arguments,1))},enumerable:!1,writable:!0,configurable:!0};Object.defineProperties(Array,b)}}));TMwin.props[B].sandboxes[a.script.id]="sandbox"!==TMwin.use.proxy||A?R():X();TMwin.props[B].elements[a.script.id]=
r;D&&console.debug("env: execute script "+d.name+" @ the "+(A?"un":TMwin.use.safeContext?"":"pseudo-")+"safe context now!");Y(d,a.code,a.requires,TMwin.props[B],A);p.push(function(){g.postMessage({method:"removeStorageListener",uuid:e,storage:c,id:TM_context_id});try{g.disconnect(),g=null}catch(d){}a=b=null})};m.extension.onMessage.addListener(function(a,b,c){if(a.id&&a.id!=TM_context_id)console.warn("env: Not for me! "+TM_context_id+"!="+a.id);else if(b=window.self==window.top,"executeScript"==a.method)b=
function(){$(a);c({})},"document-start"==a.script.options.run_at?(D&&console.debug("env: run '"+a.script.name+"' ASAP -> document-start"),b()):"document-body"==a.script.options.run_at?(D&&console.debug("env: schedule '"+a.script.name+"' for document-body"),J(b,a.script.id)):(D&&console.debug("env: schedule '"+a.script.name+"' for document-end"),Z(b,a.script.id,a.script.name));else if("onLoad"==a.method){TMwin.domContentLoaded=!0;z();c({});var e=null,d=function(){l=e=null};p.push(function(){e&&window.clearTimeout(e);
d()});e=window.setTimeout(d,2E3)}else b&&("loadUrl"==a.method?(window.location=a.url,c({})):"reload"==a.method?(window.location.reload(),c({})):"confirm"==a.method?window.setTimeout(function(){var b=confirm(a.msg);c({confirm:b})},100):"showMsg"==a.method?window.setTimeout(function(){window.setTimeout(function(){alert(a.msg)},1);c({})},100):console.log("env: unknown method "+a.method))});(function(){window.HTMLDocument.prototype.__evaluate||(window.HTMLDocument.prototype.__evaluate=window.HTMLDocument.prototype.evaluate,
window.HTMLDocument.prototype.evaluate=function(a,b,c,e,d){b||(b=this);var g;if("undefined"!=typeof XPathResult){try{g=this.__evaluate(a,b,c,e,d)}catch(k){}var f=!0;try{f&=!g.snapshotLength}catch(h){}try{f&=!g.singleNodeValue}catch(l){}f&&"."!=a.charAt(0)&&!C(b)&&(a=("/"==a.charAt(0)?".":"./")+a,g=this.__evaluate(a,b,c,e,d))}else g=b.selectNodes(xpathExpr);return g},p.push(function(){window.HTMLDocument.prototype.evaluate=window.HTMLDocument.prototype.__evaluate}))})();(function(){for(var a=[window.HTMLDocument.prototype,
window.__proto__],b=[],c=0;c<a.length;c++)(function(){var e=a[c];e.__addEventListener||(e.__addEventListener=e.addEventListener,e.__removeEventListener=e.removeEventListener,e.removeEventListener=function(a,b,c){"DOMNodeInserted"==a&&l&&l.running==b&&(l.running=null);this.__removeEventListener(a,b,c)},e.addEventListener=function(a,c,e){var f=!0;if("load"==a||"DOMContentLoaded"==a||"DOMNodeInserted"==a){var h=null,p=this;try{h=K(arguments.callee)}catch(m){D&&console.error("env: Error: event "+a,m)}if(h){var t=
null;"load"==a?TMwin.loadHappened&&(t=function(){y("load",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:window.Event.AT_TARGET,attrChange:MutationEvent.ADDITION,target:document,relatedNode:document,srcElement:document},c,p)},f=!1,b.push(t)):"DOMContentLoaded"==a?TMwin.domContentLoaded&&(t=function(){y("DOMContentLoaded",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:window.Event.AT_TARGET,attrChange:MutationEvent.ADDITION,target:document,relatedNode:document,srcElement:document},
c,p)},f=!1,b.splice(0,0,t)):"DOMNodeInserted"==a&&l&&!l.done[h]&&(l.done[h]=!0,t=function(){var b="document-start"!=h.run_at&&"document-body"!=h.run_at;l.running=c;a:if(l)for(var f=l.events.length,m=0;m<f;m++)if(b&&!l.events[m].domContentLoaded||y("DOMNodeInserted",{attrName:"",newValue:"",prevValue:"",eventPhase:window.Event.AT_TARGET,target:l.events[m].event.target,relatedNode:l.events[m].event.relatedNode,srcElement:l.events[m].event.srcElement},c,p),!l.running)break a;l.running&&p.__addEventListener(a,
c,e);l.running=null},b.push(t));t&&(window.setTimeout(function(){if(b.length){var a=b[0];b=b.slice(1);a()}},1),f=!1)}}f&&this.__addEventListener(a,c,e)},p.push(function(){e.removeEventListener=e.__removeEventListener;e.addEventListener=e.__addEventListener}))})();TMwin.windowProps.__addEventListener={proto:!0};TMwin.windowProps.__removeEventListener={proto:!0}})();(function(){TMwin.use.safeContext&&!Object.getOwnPropertyDescriptor(window,"content")&&Object.defineProperties(window,{content:{get:function(){return window.top},
enumerable:!0,configurable:!1}})})();(function(){TMwin.use.safeContext&&(window.open=function(a){var b="__o__"+TM_context_id;a="window."+b+' = window.open(decodeURI("'+encodeURI(a)+'"));';TM_do(a);a=unsafeWindow[b];delete unsafeWindow[b];return a},p.push(function(){window.open=null}))})();(function(){TMwin.use.safeContext&&!window.__setTimeout&&(window.__setTimeout=window.setTimeout,window.__setInterval=window.setInterval,window.setTimeout=function(){var a=arguments,b=a[0];"string"===typeof b&&(a[0]=
function(){TM_do(b)});return __setTimeout.apply(this,a)},window.setInterval=function(){var a=arguments,b=a[0];"string"===typeof b&&(a[0]=function(){TM_do(b)});return __setInterval.apply(this,a)},p.push(function(){window.setTimeout=window.__setTimeout;window.setInterval=window.__setInterval}))})();document.addEventListener("DOMNodeInserted",G,!1);document.addEventListener("DOMContentLoaded",F,!1);document.addEventListener("load",H,!1);window.addEventListener("unload",I,!1);D&&console.debug("env: initialized (content, id:"+
TM_context_id+", "+window.location.origin+window.location.pathname+") ")});
