Registry.require(["helper","convert","compat"],function(){var r=Registry.get("convert"),h=Registry.get("helper"),f=Registry.get("compat"),m=function(a){var b=null;a=encodeURI(a);return b=(b=a.match(/[a-zA-Z0-9]/g))?b.join(""):h.filter(r.Base64.encode(a),/[a-zA-Z0-9]/g)},n=function(){this.observers=[];this.description=this.homepage=this.namespace=this.name=this.updateURL=this.downloadURL=this.fileURL=this.icon64=this.icon=null;this.system=!1;this.enabled=!0;this.position=0;this.grant=[];this.requires=
[];this.includes=[];this.matches=[];this.excludes=[];this.resources=[];this.lastModified=this.lastUpdated=0;this.sync={imported:!1};this.options={comment:null,compatopts_for_requires:!0,compat_wrappedjsobject:!1,compat_metadata:!1,compat_foreach:!1,compat_arrayleft:!1,compat_prototypes:!1,compat_uW_gmonkey:!1,compat_forvarin:!1,noframes:null,awareOfChrome:!1,run_at:null,user_agent:"",override:{includes:!1,merge_includes:!0,use_includes:[],orig_includes:[],matches:!1,merge_matches:!0,use_matches:[],
orig_matches:[],excludes:!1,merge_excludes:!0,use_excludes:[],orig_excludes:[]}}},k={Script:n,getScriptId:m,processMetaHeader:function(a){var b={},d=["uso:hash","version","name"];a=a.replace(/\'/gi,"").replace(/\"/gi,"");a=a.replace(/\t/gi,"    ");a=a.replace(/\r/gi,"");for(var l in d)b[d[l]]=h.getStringBetweenTags(a,"@"+d[l],"\n").trim();return b},processHeader:function(a){var b=new n,d="name namespace version author copyright description".split(" "),l=["iconURL","defaulticon","icon"],f=["icon64URL",
"icon64"],k=["homepageURL","homepage","website","source"];a=a.replace(/\'/g,"").replace(/\"/g,"");a=a.replace(/\t/g,"    ");a=a.replace(/\r/g,"\n");a=a.replace(/\n\n+/g,"\n");a=a.replace(/[^|\n][ \t]+\/\//g,"//");var e,g,p,c,q=a.split("\n");for(p in q){a=q[p].replace(/^[\t\s]*\/\//gi,"").replace(/^[\t\s]*/gi,"").replace(/\s\s+/gi," ");c=!1;for(g in d)-1!=a.search(RegExp("^@"+d[g]+"[\\t\\s]"))&&(b[d[g]]=b[d[g]]||h.getStringBetweenTags(a,"@"+d[g]).trim());for(g in f)if(e=h.getStringBetweenTags(a,"@"+
f[g]).trim(),""!=e){b.icon64=b.icon64||e;c=!0;break}if(!c){for(g in l)if(e=h.getStringBetweenTags(a,"@"+l[g]).trim(),""!=e){b.icon=b.icon||e;c=!0;break}if(!c){for(g in k)if(e=h.getStringBetweenTags(a,"@"+k[g]).trim(),""!=e){b.homepage=b.homepage||e;c=!0;break}c||(-1!=a.search(/^@include[\t\s]/)&&(c=a.replace(/^@include/gi,"").trim().replace(/ /gi,"%20").replace(/[\b\r\n]/gi,""),""!=c.trim()&&b.includes.push(c)),-1!=a.search(/^@match[\t\s]/)&&(c=a.replace(/^@match/gi,"").trim().replace(/ /gi,"%20").replace(/[ \b\r\n]/gi,
""),""!=c.trim()&&b.matches.push(c),b.options.awareOfChrome=!0),-1!=a.search(/^@exclude[\t\s]/)&&(c=a.replace(/^@exclude/gi,"").trim().replace(/ /gi,"%20").replace(/[ \b\r\n]/gi,""),""!=c.trim()&&b.excludes.push(c)),-1!=a.search(/^@require[\t\s]/)&&(c=a.replace(/^@require/gi,"").trim().replace(/ /gi,"%20").replace(/[ \b\r\n]/gi,""),e={url:c,loaded:!1,textContent:""},""!=c.trim()&&b.requires.push(e)),-1!=a.search(/^@resource[\t\s]/)&&(c=a.replace(/^@resource/gi,"").replace(/[\r\n]/gi,""),e=c.trim().split(" "),
2<=e.length&&b.resources.push({name:e[0],url:e[1],loaded:!1})),-1!=a.search(/^@run-at[\t\s]/)&&(c=a.replace(/^@run-at/gi,"").replace(/[ \b\r\n]/gi,""),""!=c.trim()&&(b.options.run_at=b.options.run_at||c.trim())),-1!=a.search(/^@user-agent[\t\s]/)&&(c=a.replace(/^@user-agent/gi,"").trim().replace(/[\r\n]/gi,""),""!=c.trim()&&(b.options.user_agent=b.options.user_agent||c.trim())),-1!=a.search(/^@noframes[\t\s\r\n]?/)&&(b.options.noframes=!0),-1!=a.search(/^@nocompat[\t\s\r\n]?/)&&(b.options.awareOfChrome=
!0),-1!=a.search(/^@updateURL[\t\s]/)&&(c=a.replace(/^@updateURL/gi,"").trim().replace(/[ \b\r\n]/gi,""),""!=c.trim()&&(b.updateURL=b.updateURL||c)),-1!=a.search(/^@downloadURL[\t\s]/)&&(c=a.replace(/^@downloadURL/gi,"").trim().replace(/[ \b\r\n]/gi,""),""!=c.trim()&&(b.downloadURL=b.downloadURL||c)),-1!=a.search(/^@grant[\t\s]/)&&(c=a.replace(/^@grant/gi,"").trim().replace(/[\b\r\n]/gi,""),""!=c.trim()&&b.grant.push(c)))}}}b.name&&(b.id=m(b.name));b.version||(b.version="0.0");return b},getHeaderTags:function(){return{start:"==UserScript==",
stop:"==/UserScript=="}},getHeader:function(a){var b=h.getStringBetweenTags(a,"==UserScript==","==/UserScript==");if(!b||""==b)return null;var d=a.search("==UserScript=="),f=a.search("<html>");a=a.search("<body>");return 0<f&&f<d||0<a&&a<d?null:b},createScriptFromSrc:function(a){a=a.replace(/(\r\n|\n|\r)/gm,"\n");var b=k.getHeader(a);if(!b)return{};var d=k.processHeader(b);d.textContent=a;d.header=b;d.options.awareOfChrome||(d.options.compat_wrappedjsobject=a!=f.unWrappedJsObjectify(a),d.options.compat_metadata=
a!=f.unMetaDataify(a),d.options.compat_foreach=a!=f.unEachify(a),d.options.compat_arrayleft=a!=f.unArrayOnLeftSideify(a),d.options.compat_prototypes=f.findPrototypes(a));-1!=a.search("unsafeWindow.gmonkey")&&(d.options.compat_uW_gmonkey=!0);return d}};Registry.register("parser","48",k)});
